// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error ListQueues, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.BclExtensions.Tests")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.BclExtensions.Tests.Collections.Generic")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.BclExtensions.Tests.IO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.BclExtensions.Tests.Security")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.BclExtensions.Tests.Xml.Serialization")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "StealFocus.BclExtensions.Tests.Xml")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "InDifferent", Scope = "member", Target = "StealFocus.BclExtensions.Tests.StringExtensionsTests.#UnitTest_That_Generated_Guids_Are_Not_The_Same_For_The_Same_String_In_Different_Namespaces()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "ANon", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_A_Non_Assembly_Is_Not_Reported_As_An_Assembly()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Acls", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_Acls_Will_Copy()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.StringExtensionsTests.#UnitTest_That_Generated_Guids_Are_Not_The_Same_For_The_Same_String_In_Different_Namespaces()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.StringExtensionsTests.#UnitTest_That_Generated_Guids_Are_Not_The_Same_For_Different_Strings_In_The_Same_Namespaces()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.StringExtensionsTests.#UnitTest_That_Generated_Guids_Are_The_Same_For_The_Same_String_In_The_Same_Namespace()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.GlobalAssemblyCacheTests.#UnitTest_That_Assemblies_Are_Found_In_The_Gac()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_A_Non_Assembly_Is_Not_Reported_As_An_Assembly()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_Acls_Will_Copy()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_An_Assembly_Is_Reported_As_An_Assembly()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_Two_Different_Files_Are_Not_Reported_As_The_Same()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#IntegrationTest_That_Two_Identical_Files_Are_Reported_As_The_Same()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#UnitTest_That_Compute_Hash_With_Invalid_File_Path_Throws_BclExtensionsException()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.IO.FileSystemTest.#UnitTest_That_Compute_Hash_With_Null_File_Path_Throws_ArgumentNullException()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Security.ImpersonationTests.#IntegrationTest_That_Credentials_Are_Impersonated()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Collections.Generic.SerializableDictionaryTests.#UnitTest_That_Dictionary_Can_Deserialize()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Collections.Generic.SerializableDictionaryTests.#UnitTest_That_Dictionary_Can_Serialize()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.Serialization.SimpleXmlSerializerTest.#UnitTest_That_Something_Will_Deserialize()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.Serialization.SimpleXmlSerializerTest.#UnitTest_That_Something_Will_Deserialize_With_Xml_Namespace()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.Serialization.SimpleXmlSerializerTest.#UnitTest_That_Something_Will_Serialize()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.Serialization.SimpleXmlSerializerTest.#UnitTest_That_Something_Will_Serialize_With_Xml_Namespace()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.XmlDocumentExtensionsTests.#UnitTest_That_An_Element_Can_Be_Added()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.XmlValidatorTest.#UnitTest_Validating_An_Xml_Document_Against_A_Schema()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Xml.XmlValidatorTest.#UnitTest_Validating_With_Null_Parameters_Throws_ArgumentNullException()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.IsolatedStorageCacheTests.#UnitTest_That_After_Adding_Then_Contains_Is_True_And_After_Clear_Then_Contains_Is_False()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.CacheTests`1.#UnitTest_That_After_Adding_Then_Contains_Is_True_And_Get_Returns_The_Same_Item()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.CacheTests`1.#UnitTest_That_After_Adding_Then_Expiring_Contains_Is_False()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.CacheTests`1.#UnitTest_That_After_Adding_Then_Expiring_Get_Is_Null()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.CacheTests`1.#UnitTest_That_Without_Adding_Then_Contains_Is_False_And_Get_Returns_Null()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.InMemoryCacheTests.#UnitTest_That_After_Adding_Then_Contains_Is_True_And_After_Clear_Then_Contains_Is_False()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.IsolatedStorageCacheTests.#UnitTest_Add_Lots_Of_Items_To_Cache_And_Retrieve_From_Isolated_Storage_With_A_Different_Cache_Instance()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.IsolatedStorageCacheTests.#UnitTest_Add_To_Cache_And_Retrieve_From_Isolated_Storage_With_A_Different_Cache_Instance()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.IsolatedStorageCacheTests.#UnitTest_Cache_Load_With_Invalid_Type_In_Dictionary()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.Caching.HttpRuntimeCacheTests.#UnitTest_That_After_Adding_Then_Contains_Is_True_And_Clear_Throws_NotSupportedException()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "StealFocus.BclExtensions.Tests.StringExtensionsTests.#UnitTest_That_Strings_Of_Up_To_Five_Characters_In_Length_Never_Generate_Duplicates()")]
